# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zRoGCd9xtdsJQ8m6_REVB2MCDkFy1jb9
"""

#project
celsius = float(input("enter temperature in celsius: "))
farenheit = (celsius * 9/5) + 32
print('%.2f Celsius is: %0.2f Farenheit' %(celsius, farenheit))

